### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by netochaves** [teresinahc/carambolo#29]
- For CI we could use travis CI or circleCI, some usefull links bellow
	- Travis: https://medium.com/full-taxx/how-to-setup-travis-ci-for-a-rails-application-78a453963300
	- CircleCI: https://circleci.com/docs/2.0/language-ruby/

- On CD I think that Heroku is a good choice but feel free to propose another one.
	- https://devcenter.heroku.com/articles/getting-started-with-rails5

**Comment by aruniverse** [comment]
Have you looked into using github actions? I can take a look  if youre ok with that

**Comment by netochaves** [comment]
Hi @aruniverse. Sure you can, feel free to discuss more about here or open a PR.

**Comment by aruniverse** [comment]
So I started working on setting up the ci/cd workflow. Not too familiar with ruby. Please take a look at the PR, and let me know if you notice anything that stands out immediately.

**Comment by jclopezdev** [comment]
Hi @netochaves, I created this PR #37 to add the CircleCI config file, but you need to set up the project in the following link, and also I noticed that some specs are broken 😬 

https://circleci.com/setup-project/gh/teresinahc/carambolo
