### ISSUE TITLE
Mostrar apenas as `entradas` do usuário corrente.

### ISSUE THREAD

**Issue by marclerodrigues** [teresinahc/carambolo#7]
![photo5170656620680685643](https://user-images.githubusercontent.com/8514920/67147286-f3f63e80-f269-11e9-8e19-0a41b403334d.jpg)

**Comment by raicg** [comment]
PR made https://github.com/marclerodrigues/carambolo/pull/19

this feature needs the relation between users and entries, so it's needed accept the PR https://github.com/marclerodrigues/carambolo/pull/18
